name: Garden City Ruby Conference 2015
description: Bangalore's own Ruby Conference is happening on Saturday, January 10th, 2015"><!-- Facebook-->
#url: http://gardencityruby.org/
timezone:    Asia/Kolkata

markdown: kramdown

kramdown:
  parse_block_html: true
  parse_span_html: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gemfile", "Gemfile.lock", "post.template", "README.md", "vendor"]
assets:
  baseurl: /assets/
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - vendor/ruby/2.1.0/gems/bootstrap-sass-3.3.0.1/assets/javascripts
    - vendor/ruby/2.1.0/gems/bootstrap-sass-3.3.0.1/assets/stylesheets
    - vendor/ruby/2.1.0/gems/bootstrap-sass-3.3.0.1/assets/fonts
    - vendor/ruby/3.1.0/gems/bootstrap-sass-3.3.0.1/assets/images
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

links:
  schedule:
    name: Schedule
    url: /program
  speakers:
    name: Speakers
    url: /#speakers
  venue:
    name: Venue
    url: /#venue
  sponsors:
    name: Sponsors
    url: /#sponsors
  oss:
    name: GCRC <span class='brand-red'>♥</span> OSS
    url: /open-source-love
  code:
    name: Code of Conduct
    url: /code-of-conduct
  ticket:
    name: Buy a Ticket
    url: 'http://gcrc.doattend.com'
